const VISIBLE_ROWS = 40;
const OVERSCAN_ROWS = 10;
const LARGE_FILE_THRESHOLD = 1 * 1024 * 1024;
const SCROLL_HEIGHT = 8_000_000;
const VIEWPORT_HEIGHT = 600;
const ROW_HEIGHT = 24;
export { VISIBLE_ROWS, OVERSCAN_ROWS, LARGE_FILE_THRESHOLD, ROW_HEIGHT, SCROLL_HEIGHT, VIEWPORT_HEIGHT };